spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
      password: root
      username: root

  profiles:
    active: dev