spring:
  application:
    name:auth-service
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/auth_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  profiles.active: test
app:
  jwt-secret:
    daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds:
    604800000

