spring:
  application:
    name: file-upload
  datasource:
    url: postgresql://localhost:5432/file_upload
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
      show_sql: true
  profiles:
    active: test
minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket-name: file-upload
  region: us-east-1
  secure: false
  port: 9000