spring:
  application:
    name: axon-starter
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/bank
    name: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: bank
