spring:
  application:
    name: security-auth
  datasource:
    url: jdbc:mysql://localhost:3306/login_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: test